import type {ChildProcess} from 'node:child_process';
import {expectType, expectError, expectAssignable} from 'tsd';
import {execa, type Result, type Subprocess} from '../../index.js';

const subprocess = execa('unicorns');
expectAssignable<Subprocess>(subprocess);
expectType<Result<{}>>(await subprocess);

expectType<number | undefined>(subprocess.pid);
expectType<ChildProcess>(subprocess.nodeChildProcess);
subprocess.nodeChildProcess.on('exit', () => undefined);
subprocess.nodeChildProcess.once('exit', () => undefined);
subprocess.nodeChildProcess.ref();
subprocess.nodeChildProcess.unref();
subprocess.nodeChildProcess.send('message');
subprocess.nodeChildProcess.disconnect();
expectType<boolean>(subprocess.nodeChildProcess.connected);
expectType<number | null>(subprocess.nodeChildProcess.exitCode);
expectType<NodeJS.Signals | null>(subprocess.nodeChildProcess.signalCode);
expectType<boolean>(subprocess.nodeChildProcess.killed);
expectType<string[]>(subprocess.nodeChildProcess.spawnargs);
expectType<string>(subprocess.nodeChildProcess.spawnfile);
expectError(subprocess.on('exit', () => undefined));
expectError(subprocess.once('exit', () => undefined));
expectError(subprocess.ref());
expectError(subprocess.unref());
expectError(subprocess.send('message'));
expectError(subprocess.disconnect());
expectError(subprocess.connected);
expectError(subprocess.channel);
expectError(subprocess.exitCode);
expectError(subprocess.signalCode);
expectError(subprocess.killed);
expectError(subprocess.spawnargs);
expectError(subprocess.spawnfile);

expectType<boolean>(subprocess.kill());
subprocess.kill('SIGKILL');
subprocess.kill(undefined);
subprocess.kill(new Error('test'));
subprocess.kill('SIGKILL', new Error('test'));
subprocess.kill(undefined, new Error('test'));
expectError(subprocess.kill(null));
expectError(subprocess.kill(0n));
expectError(subprocess.kill('Sigkill'));
expectError(subprocess.kill('sigkill'));
expectError(subprocess.kill('SIGOTHER'));
expectError(subprocess.kill('SIGEMT'));
expectError(subprocess.kill('SIGCLD'));
expectError(subprocess.kill('SIGRT1'));
expectError(subprocess.kill([new Error('test')]));
expectError(subprocess.kill({message: 'test'}));
expectError(subprocess.kill(undefined, {}));
expectError(subprocess.kill('SIGKILL', {}));
expectError(subprocess.kill(null, new Error('test')));

const ipcSubprocess = execa('unicorns', {ipc: true});
expectAssignable<Subprocess>(ipcSubprocess);
