#!/usr/bin/env node
const fs = require('fs');
const execa = require('..');

const fd = fs.openSync(process.argv[2], 'w');

const cp = execa('noop', ['foo'], {
	detached: true,
	stdio: ['ignore', fd]
});
cp.unref();

process.exit();
