#!/usr/bin/env node
'use strict';
const execa = require('..');

const cleanup = process.argv[2] === 'true';
const subprocess = execa('node', ['./fixtures/forever'], {cleanup});
process.send(subprocess.pid);
