#!/usr/bin/env node
'use strict';

process.on('SIGTERM', () => {
  console.log('got sigterm but we ignore it');
});

process.send('process is launched');

setInterval(() => {
  // Run forever
}, 20000);
