name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 23
          - 18
        os:
          - ubuntu
          - macos
          - windows
    steps:
      - uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --cache --verbose --no-progress --include-fragments --exclude packagephobia --exclude /pull/ --exclude linkedin --exclude file:///test --exclude invalid.com '*.md' 'docs/*.md' '.github/**/*.md' '*.json' '*.js' 'lib/**/*.js' 'test/**/*.js' '*.ts' 'test-d/**/*.ts'
          fail: true
        if: ${{ matrix.os == 'ubuntu' && matrix.node-version == 23 }}
      - run: npm run lint
      - run: npm run type
      - run: npm run unit
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: '${{ matrix.os }}, node-${{ matrix.node-version }}'
          fail_ci_if_error: false
          verbose: true
