name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.0.0
          - 16.4.0
          - 14.18.0
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 18.0.0
        with:
          fail_ci_if_error: true
